version = 0.1

[default.build.parameters]
build_dir = 'C:\Users\Admin\Desktop\Incedo\AI Mini Project\portfolio-risk-alert-system\.aws-sam\build'
cache_dir = 'C:\Users\Admin\Desktop\Incedo\AI Mini Project\portfolio-risk-alert-system\.aws-sam\cache'

[default.deploy.parameters]
stack_name = "portfolio-risk-alert-system"
resolve_s3 = true
s3_prefix = "portfolio-risk-alert-system"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "AIProvider=\"groq\" AIModel=\"llama-3.1-8b-instant\" AIAPIUrl=\"https://api.groq.com/openai/v1/chat/completions\" AIThrottleMs=\"2500\" AIMaxRetries=\"2\""

[default.global.parameters]
region = "us-east-1"
